import { createElement } from 'lwc';
import Noob4ApiDecoratorParentToChild from 'c/noob4ApiDecoratorParentToChild';

describe('c-noob4-api-decorator-parent-to-child', () => {
    afterEach(() => {
        // The jsdom instance is shared across test cases in a single file so reset the DOM
        while (document.body.firstChild) {
            document.body.removeChild(document.body.firstChild);
        }
    });

    it('TODO: test case generated by CLI command, please fill in test logic', () => {
        // Arrange
        const element = createElement('c-noob4-api-decorator-parent-to-child', {
            is: Noob4ApiDecoratorParentToChild
        });

        // Act
        document.body.appendChild(element);

        // Assert
        // const div = element.shadowRoot.querySelector('div');
        expect(1).toBe(1);
    });
});