public class ProjectTaskClass
{
    /*
     public static void isMapping(List<Project__c> newList)
    {
        List<Project_Task__c> ProTaskList = new List<Project_Task__c>();
        
        
        for(Project__c eachProjectObject :newList)
        {
           
            for(Integer i=0;i<5;i++)
       		 {
           		 List<Project_Task__c> ProjectTaskObject = new List<Project_Task__c>();
                 
                 for( Project_Task__c ProjectTaskLoop :ProjectTaskObject)
                 {
                      ProjectTaskLoop.Type__c = eachProjectObject.Id;
                 
            	ProjectTaskLoop.Project__c = eachProjectObject.Id;
              
                 ProTaskList.add(ProjectTaskLoop);
                 }
                
                   
        	}
           
        }
        
        insert ProTaskList;   
    }
    */

}